name: Sync Upstream

on:
  schedule:
    # 每小时自动检查一次
    - cron: "0 * * * *"

  # 允许在 Actions 页面手动执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync ${{ github.repository }} \
            --branch main
